# Generated by Django 4.2.24 on 2025-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0003_apipermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apipermission",
            name="route",
            field=models.CharField(
                choices=[("admin/", "admin/"), ("api/auth/", "api/auth/")],
                max_length=255,
                verbose_name="Rota",
            ),
        ),
    ]
