# Generated by Django 4.2.24 on 2025-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0005_alter_apipermission_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="apipermission",
            name="mensagem",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Mensagem de negação",
            ),
        ),
    ]
